### ISSUE TITLE
[OTHER] Add warning to Anti-Monitoring List in Readme

### ISSUE THREAD

**Issue by MaxelaZG** [celenityy/bugs#30]
The Anti-Monitoring list contains blockages to Google "Find My Device" and Apple Find My, which may be useful to recover a device in case it's lost.

A warning in README would be beneficial to make potential users aware, especially the standard list is "recommended" for most.  :)

**Comment by celenityy** [comment]
Good point - I didn't think about it from that perspective, but you're right, I probably should add a heads up about that so users who rely on this functionality can whitelist the domains required. 

I could consider moving these domains off of `Monitoring`, but I think it makes sense to keep for now as it falls in line with BadBlock's goals (Ex. Instead of this Find My being enabled by default or otherwise without user consent, the user makes an active choice to enable it by whitelisting the domains). 

Will definitely add a warning though, thanks for your input!

**Comment by celenityy** [comment]
@maxela-2001 Does this look good?

**Comment by celenityy** [comment]
Will go ahead and close this… thanks again for the report! If you have any other feedback please LMK

**Comment by celenityy** [comment]
FWIW this will be revised very soon. I'm planning to split the 'Find My' domains to their own separate list, which will **only** be included in BadBlock+. Anti-Monitoring will solely cover remote desktop/MDM/stalkerware/etc, and will still be part of BadBlock & BadBlock+.

**Comment by celenityy** [comment]
Migrated to our new issue tracker at https://codeberg.org/celenity/bugs/issues/30, hope to see you there!
